#!/bin/bash
echo "\r\nEnvironmental Variables:\r\n"
echo "My home directory is    | $HOME"
echo "My executable path is   | $PATH"
echo "Current language is     | $LANG"
echo "Current directory is    | $PWD"
echo "Login Terminal type is  | $TERM"
echo "BASH executable path is | $SHELL"
echo "Logged in User name is  | $USER"
echo "  ...second try on name | $USERNAME"
echo "Current user's group is | $GROUP"
echo "Current display name is | $DISPLAY"
echo "Terminal Column * Line  | $COLUMNS * $LINES"
echo "$PS1"
echo "$PS2"
echo "$PS3"
echo "$PS4"
echo "$BASH"
echo "$BASH_VERSION"
echo "$HISTFILE"
echo "$HISTFILESIZE"
echo "$HISTSIZE"
echo "$HOSTNAME"
echo "$HOSTTYPE"
echo "machine type:       | $MACHTYPE"
echo "mail spool path:    | $MAIL"
echo "log name:           | $LOGNAME"
echo "runtime in seconds: | $SECONDS"
echo "user UID:           | $UID"
echo "type of OS:         | $OSTYPE"